src/Web/TaxiDinamica.Web/Areas/Administration/Controllers/ServicesController.cs
namespace TaxiDinamica.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;

    using TaxiDinamica.Services.Data.Categories;
    using TaxiDinamica.Services.Data.Partners;
    using TaxiDinamica.Services.Data.PartnerServicesServices;
    using TaxiDinamica.Services.Data.Services;
    using TaxiDinamica.Web.ViewModels.Common.SelectLists;
    using TaxiDinamica.Web.ViewModels.Services;

    public class ServicesController : AdministrationController
    {
        private readonly IServicesService servicesService;
        private readonly ICategoriesService categoriesService;
        private readonly IPartnersService partnersService;
        private readonly IPartnerServicesService partnerServicesService;

        public ServicesController(
            IServicesService servicesService,
            ICategoriesService categoriesService,
            IPartnersService partnersService,
            IPartnerServicesService partnerServicesService)
        {
            this.servicesService = servicesService;
            this.categoriesService = categoriesService;
            this.partnersService = partnersService;
            this.partnerServicesService = partnerServicesService;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = new ServicesListViewModel
            {
                Services = await this.servicesService.GetAllAsync<ServiceViewModel>(),
            };
            return this.View(viewModel);
        }

        public async Task<IActionResult> AddService()
        {
            var categories = await this.categoriesService.GetAllAsync<CategorySelectListViewModel>();
            this.ViewData["Categories"] = new SelectList(categories, "Id", "Name");

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> AddService(ServiceInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            // Add Service
            var serviceId = await this.servicesService.AddAsync(input.Name, input.CategoryId, input.Description);

            // Add the Service to all Partners in the Category
            var partnersIds = await this.partnersService.GetAllIdsByCategoryAsync(input.CategoryId);
            await this.partnerServicesService.AddAsync(partnersIds, serviceId);

            return this.RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteService(int id)
        {
            await this.servicesService.DeleteAsync(id);

            return this.RedirectToAction("Index");
        }
    }
}

src/Web/TaxiDinamica.Web/Areas/Administration/Views/Services/AddService.cshtml
@model TaxiDinamica.Web.ViewModels.Services.ServiceInputModel
@{
    this.ViewData["Title"] = "Nuevo Servicio";
    var categories = this.ViewData["Categories"] as SelectList;
}

<div class="col-lg-6">
    <h2>Añadir Nuevo Servicio</h2>
    <form method="post" enctype="multipart/form-data" class="pt-4">
        <div class="form-group row">
            <label class="col-sm-4 col-form-label">Nombre</label>
            <div class="col-sm-8">
                <input type="text" asp-for="@Model.Name" class="form-control" required="required">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-4 col-form-label">Categoría</label>
            <div class="col-sm-8">
                <select asp-for="@Model.CategoryId" class="form-control" asp-items="@categories">
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-4 col-form-label">Descripción</label>
            <div class="col-sm-8">
                <textarea type="text" asp-for="@Model.Description" class="form-control" required="required"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 text-right">
                <button type="submit" class="btn btn-success" asp-area="Administration" asp-controller="Services"
                    asp-action="AddService">
                    Añadir Servicio
                </button>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-danger" asp-area="Administration" asp-controller="Services"
                    asp-action="Index">Cancelar</a>
            </div>
        </div>
    </form>
</div>

src/Web/TaxiDinamica.Web/Areas/Administration/Views/Services/Index.cshtml
@model TaxiDinamica.Web.ViewModels.Services.ServicesListViewModel
@using TaxiDinamica.Common
@{
    this.ViewData["Title"] = "Servicios";
}

<h2>
    Todos los Servicios (@Model.Services.Count())
    <span>
        <a class="btn btn-info" asp-area="Administration" asp-controller="Services" asp-action="AddService">Añadir Nuevo
            Servicio</a>
    </span>
</h2>

<table class="table table-hover table-bordered table-striped">
    <thead class="thead-light">
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Categoría</th>
            <th scope="col">Descripción</th>
            <th scope="col">Taxis</th>
            <th scope="col">Citas</th>
            <th scope="col">Opciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var service in this.Model.Services)
        {
            <tr>
                <th scope="row">@service.Name</th>
                <td>@service.CategoryName</td>
                <td>@service.Description</td>
                <td>@service.PartnersCount</td>
                <td>@service.AppointmentsCount</td>
                <td>
                    <form method="post">
                        <button type="submit" class="btn btn-danger btn-sm" asp-area="Administration"
                        asp-controller="Services" asp-action="DeleteService" asp-route-id="@service.Id">
                            Borrar
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>