src/Web/TaxiDinamica.Web/Controllers/AppointmentsController.cs
namespace TaxiDinamica.Web.Controllers
{
    using System;
    using System.Threading.Tasks;
    using System.Text;
    using System.Text.Encodings.Web;
using System.Globalization;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Identity.UI.Services;
    using Microsoft.AspNetCore.Mvc;
    using TaxiDinamica.Data.Models;
    using TaxiDinamica.Services.Data.Appointments;
    using TaxiDinamica.Services.Data.Partners;
    using TaxiDinamica.Services.Data.PartnerServicesServices;
    using TaxiDinamica.Services.DateTimeParser;
    using TaxiDinamica.Web.ViewModels.Appointments;
    using TaxiDinamica.Web.ViewModels.PartnerServices;

    [Authorize]
    public class AppointmentsController : BaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IDateTimeParserService dateTimeParserService;
        private readonly IPartnersService partnersService;
        private readonly IAppointmentsService appointmentsService;
        private readonly IPartnerServicesService partnerServicesService;
        private readonly IEmailSender emailSender;

        public AppointmentsController(
            UserManager<ApplicationUser> userManager,
            IAppointmentsService appointmentsService,
            IPartnerServicesService partnerServicesService,
            IDateTimeParserService dateTimeParserService,
            IPartnersService partnersService,
            IEmailSender emailSender)
        {
            this.userManager = userManager;
            this.appointmentsService = appointmentsService;
            this.partnerServicesService = partnerServicesService;
            this.dateTimeParserService = dateTimeParserService;
            this.partnersService = partnersService;
            this.emailSender = emailSender;
        }

        public async Task<IActionResult> Index()
        {
            var user = await this.userManager.GetUserAsync(this.HttpContext.User);
            var userId = await this.userManager.GetUserIdAsync(user);

            var viewModel = new AppointmentsListViewModel
            {
                Appointments =
                    await this.appointmentsService.GetUpcomingByUserAsync<AppointmentViewModel>(userId),
            };
            return this.View(viewModel);
        }

        public async Task<IActionResult> MakeAnAppointment(string partnerId, int serviceId)
        {
            var partnerService = await this.partnerServicesService.GetByIdAsync<PartnerServiceSimpleViewModel>(partnerId, serviceId);
            if (partnerService == null || !partnerService.Available)
            {
                return this.View("UnavailableService");
            }

            var viewModel = new AppointmentInputModel
            {
                PartnerId = partnerId,
                ServiceId = serviceId,
            };
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> MakeAnAppointment(AppointmentInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction("MakeAnAppointment", new { input.PartnerId, input.ServiceId });
            }

            DateTime dateTime;
            try
            {
                dateTime = this.dateTimeParserService.ConvertStrings(input.Date, input.Time);
            }
            catch (System.Exception)
            {
                return this.RedirectToAction("MakeAnAppointment", new { input.PartnerId, input.ServiceId });
            }

            var user = await this.userManager.GetUserAsync(this.HttpContext.User);
            var userId = await this.userManager.GetUserIdAsync(user);

            await this.appointmentsService.AddAsync(userId, input.PartnerId, input.ServiceId, dateTime, input.AddressStart, input.AddressEnd, input.Comment, input.Price);

            var callbackUrl = this.Url.Page("/Appoinments");

            // Send Email
            var uemail = user?.Email;
            await this.emailSender.SendEmailAsync(
                uemail,
                "Cita Agendada",
                $"Haz agendado una cita exitosamente para el día {dateTime}, puedes ver los demás detalles haciendo <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>click aquí</a>.");

            return this.RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> CancelAppointment(string id)
        {
            var viewModel = await this.appointmentsService.GetByIdAsync<AppointmentViewModel>(id);

            if (viewModel == null)
            {
                return new StatusCodeResult(404);
            }

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAppointment(string id)
        {
            await this.appointmentsService.DeleteAsync(id);

            return this.RedirectToAction("Index");
        }
    }
}

src/Web/TaxiDinamica.Web/Controllers/CategoriesController.cs
namespace TaxiDinamica.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using TaxiDinamica.Services.Data.Categories;
    using TaxiDinamica.Web.ViewModels.Categories;

    public class CategoriesController : BaseController
    {
        private readonly ICategoriesService categoriesService;

        public CategoriesController(ICategoriesService categoriesService)
        {
            this.categoriesService = categoriesService;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = new CategoriesListViewModel
            {
                Categories = await this.categoriesService.GetAllAsync<CategoryViewModel>(),
            };
            return this.View(viewModel);
        }
    }
}

src/Web/TaxiDinamica.Web/Controllers/PartnersController.cs
namespace TaxiDinamica.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using TaxiDinamica.Services.Data.Categories;
    using TaxiDinamica.Services.Data.Partners;
    using TaxiDinamica.Web.ViewModels.Categories;
    using TaxiDinamica.Web.ViewModels.Common.Pagination;
    using TaxiDinamica.Web.ViewModels.Partners;

    public class PartnersController : BaseController
    {
        private readonly IPartnersService partnersService;
        private readonly ICategoriesService categoriesService;

        public PartnersController(
            IPartnersService partnersService,
            ICategoriesService categoriesService)
        {
            this.partnersService = partnersService;
            this.categoriesService = categoriesService;
        }

        public async Task<IActionResult> Index(
            int? sortId, // categoryId
            string currentFilter,
            string searchString,
            int? pageNumber)
        {
            if (sortId != null)
            {
                var category = await this.categoriesService
                    .GetByIdAsync<CategorySimpleViewModel>(sortId.Value);
                if (category == null)
                {
                    return new StatusCodeResult(404);
                }

                this.ViewData["CategoryName"] = category.Name;
            }

            this.ViewData["CurrentSort"] = sortId;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            this.ViewData["CurrentFilter"] = searchString;

            int pageSize = PageSizesConstants.Partners;
            var pageIndex = pageNumber ?? 1;

            var partners = await this.partnersService
                .GetAllWithSortingFilteringAndPagingAsync<PartnerViewModel>(searchString, sortId, pageSize, pageIndex);
            var partnersList = partners.ToList();

            var count = await this.partnersService
                .GetCountForPaginationAsync(searchString, sortId);

            var viewModel = new PartnersPaginatedListViewModel
            {
                Partners = new PaginatedList<PartnerViewModel>(partnersList, count, pageIndex, pageSize),
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> Details(string id)
        {
            var viewModel = await this.partnersService.GetByIdAsync<PartnerWithServicesViewModel>(id);

            if (viewModel == null)
            {
                return new StatusCodeResult(404);
            }

            return this.View(viewModel);
        }
    }
}

src/Web/TaxiDinamica.Web/Views/Shared/Error404.cshtml
@using TaxiDinamica.Common
@{
    this.ViewData["Title"] = "Error 404";
}

<div class="row">
    <div class="col-6">
        <div class="row">
            <div class="col-7">
                <img src="~/img/bug_fixing.svg" class="img-thumbnail" />
            </div>
            <div class="col-5 pt-2">
                <h1>Oops!</h1>
                <h2>404</h2>
                <h3>Pagina no encontrada!</h3>
            </div>
        </div>
    </div>
    <div class="col-6">
    </div>
</div>

src/Web/TaxiDinamica.Web/Views/Shared/_FooterPartial.cshtml
@using TaxiDinamica.Common
<footer id="footer" class="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row gy-4">
                <div class="col-lg-6 col-md-12 footer-info">
                    <a href="index.html" class="logo d-flex align-items-center">
                        <img src="~/img/logo.png" alt="">
                        <span>@GlobalConstants.SystemName</span>
                    </a>
                    <p>Agenda tus servicios con anticipación. Te ayudamos programar tu servicio en el horario que necesites.</p>
                    <div class="social-links mt-3">
                        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bi bi-instagram bx bxl-instagram"></i></a>
                        <a href="#" class="linkedin"><i class="bi bi-linkedin bx bxl-linkedin"></i></a>
                    </div>
                </div>

                <div class="col-lg-3 col-md-12 footer-links">
                    <h4>Accesos Rápidos</h4>
                    <ul>
                        <li><i class="bi bi-chevron-right"></i> <a asp-area="" asp-controller="Home" asp-action="Index">Inicio</a></li>
                        <li><i class="bi bi-chevron-right"></i> <a href="#">Nosotros</a></li>
                        <li><i class="bi bi-chevron-right"></i> <a href="#">Servicios</a></li>
                        <li><i class="bi bi-chevron-right"></i> <a href="#">Terminos del servicio</a></li>
                        <li><i class="bi bi-chevron-right"></i> <a asp-area="" asp-controller="Home" asp-action="Privacy">Politicas de Privacidad</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-12 footer-contact text-left text-md-center">
                    <h4>Contactenos</h4>
                    <p>
                        Calle 55 No 14 – 47 <br>
                        Bogotá DC<br>
                        Colombia<br><br>
                        <strong>Teléfono:</strong> +57 3188401247<br>
                        <strong>Correo:</strong> admin@taxidinamica.com.co<br>
                    </p>
                </div>

            </div>
        </div>
    </div>

    <div class="container">
        <div class="copyright">
            Copyright &copy;
            <script>document.write(new Date().getFullYear());</script> <strong><span>@GlobalConstants.SystemName</span></strong>. Todos
            los derechos reservados
        </div>
    </div>
</footer>

src/Web/TaxiDinamica.Web/Views/Shared/_Layout.cshtml
@using TaxiDinamica.Common
<!DOCTYPE html>
<html lang="es_CO">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <!-- Favicons -->
    <link href="~/img/favicon.png" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/lib/aos/dist/aos.css" rel="stylesheet">
        <link href="~/lib/glightbox/dist/css/glightbox.min.css" rel="stylesheet">
        <link href="~/plugins/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
        <link href="~/plugins/remixicon/remixicon.css" rel="stylesheet">
        <link href="~/css/style.css" rel="stylesheet">
    </environment>
    <environment names="Staging,Production">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/lib/aos/dist/aos.css" rel="stylesheet">
        <link href="~/lib/glightbox/dist/css/glightbox.min.css" rel="stylesheet">
        <link href="~/plugins/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
        <link href="~/plugins/remixicon/remixicon.css" rel="stylesheet">
        <link href="~/css/style.min.css" rel="stylesheet">
    </environment>
    @this.RenderSection("Styles", required: false)
</head>

<body>
    <!-- ======= Header ======= -->
    <partial name="_MenuPartial" />
    @if (this.ViewData["Title"].ToString() == "Inicio")
    {
        <!-- ======= Hero Section ======= -->
        <section id="hero" class="hero d-flex align-items-center">

            <div class="container">
                <div class="row">
                    <div class="col-lg-6 d-flex flex-column justify-content-center">
                        <h1 data-aos="fade-up">Agenda tus servicios</h1>
                        <h2 data-aos="fade-up" data-aos-delay="400">@GlobalConstants.SystemName te ayuda a programar tus servicios en cualquier horario.</h2>
                        <div data-aos="fade-up" data-aos-delay="600">
                            <div class="text-lg-start">
                                <a asp-controller="Appointments" asp-action="Index"
                                class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center">
                                    <span>Empezar ahora</span>
                                    <i class="bi bi-arrow-right"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
                        <img src="~/img/schedule-hero.svg" class="img-fluid" alt="">
                    </div>
                </div>
            </div>

        </section><!-- End Hero -->
        <main id="main">
            <div class="container">
                @this.RenderBody()
            </div>
        </main><!-- End #main -->
    }
    else
    {
        <!-- ======= Breadcrumbs ======= -->
        <section class="breadcrumbs">
            <div class="container" data-aos="fade-bottom">

                <ol>
                    <li><a href="/">Inicio</a></li>
                    <li>@this.ViewData["Title"].ToString()</li>
                </ol>
                <h2>@this.ViewData["Title"].ToString()</h2>

            </div>
        </section><!-- End Breadcrumbs -->
        <main id="main">
            <section class='@this.ViewData["cClass"]?.ToString() py-5'>
                <div class="container" data-aos="fade-up">
                    @this.RenderBody()
                </div>
            </section>
        </main><!-- End #main -->
    }


    <!-- ======= Footer ======= -->
    <partial name="_FooterPartial" />
    <!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- plugins JS Files -->
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"
            asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/aos/dist/aos.js"></script>
        <script src="~/lib/isotope-layout/dist/isotope.pkgd.min.js"></script>
        <script src="~/lib/glightbox/dist/js/glightbox.min.js"></script>
        <script src="~/plugins/purecounter/purecounter.js"></script>

        <!-- Template Main JS File -->
        <script src="~/js/main.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"
            asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/aos/dist/aos.js"></script>
        <script src="~/lib/isotope-layout/dist/isotope.pkgd.min.js"></script>
        <script src="~/lib/glightbox/dist/js/glightbox.min.js"></script>
        <script src="~/plugins/purecounter/purecounter.js"></script>

        <!-- Template Main JS File -->
        <script src="~/js/main.min.js"></script>
    </environment>
    @this.RenderSection("Scripts", required: false)
</body>

</html>

src/Web/TaxiDinamica.Web/Views/Shared/_MenuItemsPartial.cshtml
@using TaxiDinamica.Common
@using TaxiDinamica.Data.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<li><a class="nav-link scrollto active" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a></li>
@* <li><a class="nav-link scrollto" asp-area="" asp-controller="Home" asp-action="Index" asp-fragment="about">Nosotros</a></li> *@
<li class="dropdown"><a href="#"><span>Explorar</span> <i class="bi bi-chevron-down"></i></a>
    <ul>
        <li><a asp-area="" asp-controller="Categories" asp-action="Index">Categorías</a></li>
        <li><a asp-area="" asp-controller="Partners" asp-action="Index">Taxis</a></li>
    </ul>
</li>
<li><a class="nav-link scrollto" asp-area="" asp-controller="Home" asp-action="Index" asp-fragment="contact">Contacto</a></li>
<li><a class="getstarted scrollto" asp-area="" asp-controller="Categories" asp-action="Index">Agendar Cita</a></li>

<partial name="_LoginPartial" />

src/Web/TaxiDinamica.Web/Views/Shared/_MenuPartial.cshtml
@using TaxiDinamica.Common
<header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

        <a asp-area="" asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center">
            <img src="~/img/logo.png" alt="">
            <span>@GlobalConstants.SystemName</span>
        </a>

        <nav id="navbar" class="navbar">
            <ul>
                <partial name="_MenuItemsPartial" />
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->

src/Web/TaxiDinamica.Web/Views/Shared/_SearchBarPartial.cshtml
<div class="search_content d-flex flex-row align-items-center justify-content-end ml-auto">
    <form asp-area="" asp-controller="Partners" asp-action="Index" method="get" class="search_container_form">
        <input type="text" name="SearchString" class="search_container_input"
               placeholder="Search by Partner name..." value="@ViewData["currentFilter"]" required="required" />
        <button type="submit" value="Search" class="search_container_button"><i class="fa fa-search" aria-hidden="true"></i></button>
    </form>
</div>